class Error(Exception):
    def __init__(self, message) -> None:
        super().__init__(message)
        self.message = message

    def __str__(self) -> str:
        return self.message

class NotFoundError(Error):...
class LengthError(Error):...
class ParameterError(Error):...
class FoundError(Error):...
class ArgumentNotFoundError(Error):...
class EmptyDataError(Error):...
class FileSizeError(Error):...